-- Run in Supabase SQL editor

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  first_name text,
  last_name text,
  full_name text,
  phone text,
  role text default 'pending' check (role in ('pending', 'tester', 'reviewer', 'provider', 'admin')),
  accepted_terms_at timestamptz,
  created_at timestamptz default now()
);

alter table public.profiles add column if not exists first_name text;
alter table public.profiles add column if not exists last_name text;
alter table public.profiles add column if not exists phone text;

create table if not exists public.memberships (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  status text default 'pending_payment' check (status in ('pending_payment', 'paid', 'active', 'suspended')),
  square_customer_id text,
  square_subscription_id text,
  paid_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.kyc_checks (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  status text default 'pending' check (status in ('pending', 'in_review', 'approved', 'rejected')),
  provider_name text,
  reference_id text,
  reviewed_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.provider_contacts (
  id bigint generated by default as identity primary key,
  title text not null,
  network text,
  url text not null,
  contact_methods text,
  notes text,
  is_active boolean default true,
  is_verified boolean default false,
  created_by uuid references public.profiles(id),
  created_at timestamptz default now()
);

alter table public.provider_contacts add column if not exists contact_methods text;
alter table public.provider_contacts add column if not exists is_verified boolean default false;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.profiles(id),
  action text not null,
  target_user_id uuid,
  metadata jsonb,
  created_at timestamptz default now()
);

create table if not exists public.reviewer_contact_history (
  reviewer_id uuid references public.profiles(id) on delete cascade,
  provider_contact_id bigint references public.provider_contacts(id) on delete cascade,
  contacted_at timestamptz default now(),
  primary key (reviewer_id, provider_contact_id)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, first_name, last_name, full_name, phone)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', '')
  );

  insert into public.memberships (user_id)
  values (new.id);

  insert into public.kyc_checks (user_id)
  values (new.id);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.memberships enable row level security;
alter table public.kyc_checks enable row level security;
alter table public.provider_contacts enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.reviewer_contact_history enable row level security;

create or replace function public.is_admin(user_uuid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_uuid
      and role = 'admin'
  );
$$;

create policy "users read own profile"
on public.profiles
for select
using (auth.uid() = id or public.is_admin(auth.uid()));

create policy "users update own profile"
on public.profiles
for update
using (auth.uid() = id or public.is_admin(auth.uid()));

create policy "users read own membership"
on public.memberships
for select
using (auth.uid() = user_id or public.is_admin(auth.uid()));

create policy "admin upsert memberships"
on public.memberships
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "users read own kyc"
on public.kyc_checks
for select
using (auth.uid() = user_id or public.is_admin(auth.uid()));

create policy "admin upsert kyc"
on public.kyc_checks
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "members read active contacts"
on public.provider_contacts
for select
using (is_active = true);

create policy "admin manage contacts"
on public.provider_contacts
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "admin logs"
on public.admin_audit_logs
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "reviewers manage own contact history"
on public.reviewer_contact_history
for all
using (auth.uid() = reviewer_id or public.is_admin(auth.uid()))
with check (auth.uid() = reviewer_id or public.is_admin(auth.uid()));

