export type WhatsappPrefixOption = {
  flag: string;
  label: string;
  value: string;
};

export const WHATSAPP_PREFIX_OPTIONS = [
  { flag: '🇺🇸', label: 'Estados Unidos', value: 'us:+1' },
  { flag: '🇲🇽', label: 'México', value: 'mx:+52' },
  { flag: '🇨🇴', label: 'Colombia', value: 'co:+57' },
  { flag: '🇩🇴', label: 'República Dominicana', value: 'do:+1' },
  { flag: '🇪🇸', label: 'España', value: 'es:+34' },
  { flag: '🇨🇺', label: 'Cuba', value: 'cu:+53' },
  { flag: '🇦🇷', label: 'Argentina', value: 'ar:+54' },
  { flag: '🇧🇷', label: 'Brasil', value: 'br:+55' },
  { flag: '🇨🇱', label: 'Chile', value: 'cl:+56' },
  { flag: '🇵🇪', label: 'Perú', value: 'pe:+51' },
  { flag: '🇪🇨', label: 'Ecuador', value: 'ec:+593' },
  { flag: '🇨🇦', label: 'Canadá', value: 'ca:+1' },
  { flag: '🇬🇧', label: 'Reino Unido', value: 'gb:+44' },
  { flag: '🇦🇫', label: 'Afganistán', value: 'af:+93' },
  { flag: '🇦🇱', label: 'Albania', value: 'al:+355' },
  { flag: '🇩🇪', label: 'Alemania', value: 'de:+49' },
  { flag: '🇦🇩', label: 'Andorra', value: 'ad:+376' },
  { flag: '🇦🇴', label: 'Angola', value: 'ao:+244' },
  { flag: '🇦🇮', label: 'Anguila', value: 'ai:+1' },
  { flag: '🇦🇬', label: 'Antigua y Barbuda', value: 'ag:+1' },
  { flag: '🇸🇦', label: 'Arabia Saudí', value: 'sa:+966' },
  { flag: '🇩🇿', label: 'Argelia', value: 'dz:+213' },
  { flag: '🇦🇲', label: 'Armenia', value: 'am:+374' },
  { flag: '🇦🇼', label: 'Aruba', value: 'aw:+297' },
  { flag: '🇦🇺', label: 'Australia', value: 'au:+61' },
  { flag: '🇦🇹', label: 'Austria', value: 'at:+43' },
  { flag: '🇦🇿', label: 'Azerbaiyán', value: 'az:+994' },
  { flag: '🇧🇸', label: 'Bahamas', value: 'bs:+1' },
  { flag: '🇧🇩', label: 'Bangladés', value: 'bd:+880' },
  { flag: '🇧🇧', label: 'Barbados', value: 'bb:+1' },
  { flag: '🇧🇭', label: 'Baréin', value: 'bh:+973' },
  { flag: '🇧🇪', label: 'Bélgica', value: 'be:+32' },
  { flag: '🇧🇿', label: 'Belice', value: 'bz:+501' },
  { flag: '🇧🇯', label: 'Benín', value: 'bj:+229' },
  { flag: '🇧🇲', label: 'Bermudas', value: 'bm:+1' },
  { flag: '🇧🇾', label: 'Bielorrusia', value: 'by:+375' },
  { flag: '🇧🇴', label: 'Bolivia', value: 'bo:+591' },
  { flag: '🇧🇦', label: 'Bosnia y Herzegovina', value: 'ba:+387' },
  { flag: '🇧🇼', label: 'Botsuana', value: 'bw:+267' },
  { flag: '🇧🇳', label: 'Brunéi', value: 'bn:+673' },
  { flag: '🇧🇬', label: 'Bulgaria', value: 'bg:+359' },
  { flag: '🇧🇫', label: 'Burkina Faso', value: 'bf:+226' },
  { flag: '🇧🇮', label: 'Burundi', value: 'bi:+257' },
  { flag: '🇧🇹', label: 'Bután', value: 'bt:+975' },
  { flag: '🇨🇻', label: 'Cabo Verde', value: 'cv:+238' },
  { flag: '🇰🇭', label: 'Camboya', value: 'kh:+855' },
  { flag: '🇨🇲', label: 'Camerún', value: 'cm:+237' },
  { flag: '🇧🇶', label: 'Caribe neerlandés', value: 'bq:+599' },
  { flag: '🇶🇦', label: 'Catar', value: 'qa:+974' },
  { flag: '🇹🇩', label: 'Chad', value: 'td:+235' },
  { flag: '🇨🇿', label: 'Chequia', value: 'cz:+420' },
  { flag: '🇨🇳', label: 'China', value: 'cn:+86' },
  { flag: '🇨🇾', label: 'Chipre', value: 'cy:+357' },
  { flag: '🇻🇦', label: 'Ciudad del Vaticano', value: 'va:+3906698' },
  { flag: '🇰🇲', label: 'Comoras', value: 'km:+269' },
  { flag: '🇨🇬', label: 'Congo', value: 'cg:+242' },
  { flag: '🇰🇵', label: 'Corea del Norte', value: 'kp:+850' },
  { flag: '🇰🇷', label: 'Corea del Sur', value: 'kr:+82' },
  { flag: '🇨🇷', label: 'Costa Rica', value: 'cr:+506' },
  { flag: '🇨🇮', label: 'Côte d’Ivoire', value: 'ci:+225' },
  { flag: '🇭🇷', label: 'Croacia', value: 'hr:+385' },
  { flag: '🇨🇼', label: 'Curazao', value: 'cw:+599' },
  { flag: '🇩🇰', label: 'Dinamarca', value: 'dk:+45' },
  { flag: '🇩🇲', label: 'Dominica', value: 'dm:+1' },
  { flag: '🇪🇬', label: 'Egipto', value: 'eg:+20' },
  { flag: '🇸🇻', label: 'El Salvador', value: 'sv:+503' },
  { flag: '🇦🇪', label: 'Emiratos Árabes Unidos', value: 'ae:+971' },
  { flag: '🇪🇷', label: 'Eritrea', value: 'er:+291' },
  { flag: '🇸🇰', label: 'Eslovaquia', value: 'sk:+421' },
  { flag: '🇸🇮', label: 'Eslovenia', value: 'si:+386' },
  { flag: '🇪🇪', label: 'Estonia', value: 'ee:+372' },
  { flag: '🇸🇿', label: 'Esuatini', value: 'sz:+268' },
  { flag: '🇪🇹', label: 'Etiopía', value: 'et:+251' },
  { flag: '🇵🇭', label: 'Filipinas', value: 'ph:+63' },
  { flag: '🇫🇮', label: 'Finlandia', value: 'fi:+358' },
  { flag: '🇫🇯', label: 'Fiyi', value: 'fj:+679' },
  { flag: '🇫🇷', label: 'Francia', value: 'fr:+33' },
  { flag: '🇬🇦', label: 'Gabón', value: 'ga:+241' },
  { flag: '🇬🇲', label: 'Gambia', value: 'gm:+220' },
  { flag: '🇬🇪', label: 'Georgia', value: 'ge:+995' },
  { flag: '🇬🇭', label: 'Ghana', value: 'gh:+233' },
  { flag: '🇬🇮', label: 'Gibraltar', value: 'gi:+350' },
  { flag: '🇬🇩', label: 'Granada', value: 'gd:+1' },
  { flag: '🇬🇷', label: 'Grecia', value: 'gr:+30' },
  { flag: '🇬🇱', label: 'Groenlandia', value: 'gl:+299' },
  { flag: '🇬🇵', label: 'Guadalupe', value: 'gp:+590' },
  { flag: '🇬🇺', label: 'Guam', value: 'gu:+1' },
  { flag: '🇬🇹', label: 'Guatemala', value: 'gt:+502' },
  { flag: '🇬🇫', label: 'Guayana Francesa', value: 'gf:+594' },
  { flag: '🇬🇬', label: 'Guernesey', value: 'gg:+44' },
  { flag: '🇬🇳', label: 'Guinea', value: 'gn:+224' },
  { flag: '🇬🇶', label: 'Guinea Ecuatorial', value: 'gq:+240' },
  { flag: '🇬🇼', label: 'Guinea-Bisáu', value: 'gw:+245' },
  { flag: '🇬🇾', label: 'Guyana', value: 'gy:+592' },
  { flag: '🇭🇹', label: 'Haití', value: 'ht:+509' },
  { flag: '🇭🇳', label: 'Honduras', value: 'hn:+504' },
  { flag: '🇭🇺', label: 'Hungría', value: 'hu:+36' },
  { flag: '🇮🇳', label: 'India', value: 'in:+91' },
  { flag: '🇮🇩', label: 'Indonesia', value: 'id:+62' },
  { flag: '🇮🇶', label: 'Irak', value: 'iq:+964' },
  { flag: '🇮🇷', label: 'Irán', value: 'ir:+98' },
  { flag: '🇮🇪', label: 'Irlanda', value: 'ie:+353' },
  { flag: '🇧🇻', label: 'Isla Bouvet', value: 'bv:+47' },
  { flag: '🇮🇲', label: 'Isla de Man', value: 'im:+44' },
  { flag: '🇨🇽', label: 'Isla de Navidad', value: 'cx:+61' },
  { flag: '🇳🇫', label: 'Isla Norfolk', value: 'nf:+672' },
  { flag: '🇮🇸', label: 'Islandia', value: 'is:+354' },
  { flag: '🇦🇽', label: 'Islas Aland', value: 'ax:+35818' },
  { flag: '🇰🇾', label: 'Islas Caimán', value: 'ky:+1' },
  { flag: '🇨🇨', label: 'Islas Cocos', value: 'cc:+61' },
  { flag: '🇨🇰', label: 'Islas Cook', value: 'ck:+682' },
  { flag: '🇫🇴', label: 'Islas Feroe', value: 'fo:+298' },
  { flag: '🇬🇸', label: 'Islas Georgia del Sur y Sandwich del Sur', value: 'gs:+500' },
  { flag: '🇫🇰', label: 'Islas Malvinas', value: 'fk:+500' },
  { flag: '🇲🇵', label: 'Islas Marianas del Norte', value: 'mp:+1' },
  { flag: '🇲🇭', label: 'Islas Marshall', value: 'mh:+692' },
  { flag: '🇺🇲', label: 'Islas menores alejadas de EE. UU.', value: 'um:+268' },
  { flag: '🇵🇳', label: 'Islas Pitcairn', value: 'pn:+64' },
  { flag: '🇸🇧', label: 'Islas Salomón', value: 'sb:+677' },
  { flag: '🇹🇨', label: 'Islas Turcas y Caicos', value: 'tc:+1' },
  { flag: '🇻🇬', label: 'Islas Vírgenes Británicas', value: 'vg:+1' },
  { flag: '🇻🇮', label: 'Islas Vírgenes de EE. UU.', value: 'vi:+1' },
  { flag: '🇮🇱', label: 'Israel', value: 'il:+972' },
  { flag: '🇮🇹', label: 'Italia', value: 'it:+39' },
  { flag: '🇯🇲', label: 'Jamaica', value: 'jm:+1' },
  { flag: '🇯🇵', label: 'Japón', value: 'jp:+81' },
  { flag: '🇯🇪', label: 'Jersey', value: 'je:+44' },
  { flag: '🇯🇴', label: 'Jordania', value: 'jo:+962' },
  { flag: '🇰🇿', label: 'Kazajistán', value: 'kz:+7' },
  { flag: '🇰🇪', label: 'Kenia', value: 'ke:+254' },
  { flag: '🇰🇬', label: 'Kirguistán', value: 'kg:+996' },
  { flag: '🇰🇮', label: 'Kiribati', value: 'ki:+686' },
  { flag: '🇽🇰', label: 'Kosovo', value: 'xk:+383' },
  { flag: '🇰🇼', label: 'Kuwait', value: 'kw:+965' },
  { flag: '🇱🇦', label: 'Laos', value: 'la:+856' },
  { flag: '🇱🇸', label: 'Lesoto', value: 'ls:+266' },
  { flag: '🇱🇻', label: 'Letonia', value: 'lv:+371' },
  { flag: '🇱🇧', label: 'Líbano', value: 'lb:+961' },
  { flag: '🇱🇷', label: 'Liberia', value: 'lr:+231' },
  { flag: '🇱🇾', label: 'Libia', value: 'ly:+218' },
  { flag: '🇱🇮', label: 'Liechtenstein', value: 'li:+423' },
  { flag: '🇱🇹', label: 'Lituania', value: 'lt:+370' },
  { flag: '🇱🇺', label: 'Luxemburgo', value: 'lu:+352' },
  { flag: '🇲🇰', label: 'Macedonia del Norte', value: 'mk:+389' },
  { flag: '🇲🇬', label: 'Madagascar', value: 'mg:+261' },
  { flag: '🇲🇾', label: 'Malasia', value: 'my:+60' },
  { flag: '🇲🇼', label: 'Malaui', value: 'mw:+265' },
  { flag: '🇲🇻', label: 'Maldivas', value: 'mv:+960' },
  { flag: '🇲🇱', label: 'Mali', value: 'ml:+223' },
  { flag: '🇲🇹', label: 'Malta', value: 'mt:+356' },
  { flag: '🇲🇦', label: 'Marruecos', value: 'ma:+212' },
  { flag: '🇲🇶', label: 'Martinica', value: 'mq:+596' },
  { flag: '🇲🇺', label: 'Mauricio', value: 'mu:+230' },
  { flag: '🇲🇷', label: 'Mauritania', value: 'mr:+222' },
  { flag: '🇾🇹', label: 'Mayotte', value: 'yt:+262' },
  { flag: '🇫🇲', label: 'Micronesia', value: 'fm:+691' },
  { flag: '🇲🇩', label: 'Moldavia', value: 'md:+373' },
  { flag: '🇲🇨', label: 'Mónaco', value: 'mc:+377' },
  { flag: '🇲🇳', label: 'Mongolia', value: 'mn:+976' },
  { flag: '🇲🇪', label: 'Montenegro', value: 'me:+382' },
  { flag: '🇲🇸', label: 'Montserrat', value: 'ms:+1' },
  { flag: '🇲🇿', label: 'Mozambique', value: 'mz:+258' },
  { flag: '🇲🇲', label: 'Myanmar (Birmania)', value: 'mm:+95' },
  { flag: '🇳🇦', label: 'Namibia', value: 'na:+264' },
  { flag: '🇳🇷', label: 'Nauru', value: 'nr:+674' },
  { flag: '🇳🇵', label: 'Nepal', value: 'np:+977' },
  { flag: '🇳🇮', label: 'Nicaragua', value: 'ni:+505' },
  { flag: '🇳🇪', label: 'Níger', value: 'ne:+227' },
  { flag: '🇳🇬', label: 'Nigeria', value: 'ng:+234' },
  { flag: '🇳🇺', label: 'Niue', value: 'nu:+683' },
  { flag: '🇳🇴', label: 'Noruega', value: 'no:+47' },
  { flag: '🇳🇨', label: 'Nueva Caledonia', value: 'nc:+687' },
  { flag: '🇳🇿', label: 'Nueva Zelanda', value: 'nz:+64' },
  { flag: '🇴🇲', label: 'Omán', value: 'om:+968' },
  { flag: '🇳🇱', label: 'Países Bajos', value: 'nl:+31' },
  { flag: '🇵🇰', label: 'Pakistán', value: 'pk:+92' },
  { flag: '🇵🇼', label: 'Palaos', value: 'pw:+680' },
  { flag: '🇵🇦', label: 'Panamá', value: 'pa:+507' },
  { flag: '🇵🇬', label: 'Papúa Nueva Guinea', value: 'pg:+675' },
  { flag: '🇵🇾', label: 'Paraguay', value: 'py:+595' },
  { flag: '🇵🇫', label: 'Polinesia Francesa', value: 'pf:+689' },
  { flag: '🇵🇱', label: 'Polonia', value: 'pl:+48' },
  { flag: '🇵🇹', label: 'Portugal', value: 'pt:+351' },
  { flag: '🇵🇷', label: 'Puerto Rico', value: 'pr:+1' },
  { flag: '🇭🇰', label: 'RAE de Hong Kong (China)', value: 'hk:+852' },
  { flag: '🇲🇴', label: 'RAE de Macao (China)', value: 'mo:+853' },
  { flag: '🇨🇫', label: 'República Centroafricana', value: 'cf:+236' },
  { flag: '🇨🇩', label: 'República Democrática del Congo', value: 'cd:+243' },
  { flag: '🇷🇪', label: 'Reunión', value: 're:+262' },
  { flag: '🇷🇼', label: 'Ruanda', value: 'rw:+250' },
  { flag: '🇷🇴', label: 'Rumanía', value: 'ro:+40' },
  { flag: '🇷🇺', label: 'Rusia', value: 'ru:+7' },
  { flag: '🇪🇭', label: 'Sáhara Occidental', value: 'eh:+2125288' },
  { flag: '🇼🇸', label: 'Samoa', value: 'ws:+685' },
  { flag: '🇦🇸', label: 'Samoa Americana', value: 'as:+1' },
  { flag: '🇧🇱', label: 'San Bartolomé', value: 'bl:+590' },
  { flag: '🇰🇳', label: 'San Cristóbal y Nieves', value: 'kn:+1' },
  { flag: '🇸🇲', label: 'San Marino', value: 'sm:+378' },
  { flag: '🇲🇫', label: 'San Martín', value: 'mf:+590' },
  { flag: '🇵🇲', label: 'San Pedro y Miquelón', value: 'pm:+508' },
  { flag: '🇻🇨', label: 'San Vicente y las Granadinas', value: 'vc:+1' },
  { flag: '🇸🇭', label: 'Santa Elena', value: 'sh:+290' },
  { flag: '🇱🇨', label: 'Santa Lucía', value: 'lc:+1' },
  { flag: '🇸🇹', label: 'Santo Tomé y Príncipe', value: 'st:+239' },
  { flag: '🇸🇳', label: 'Senegal', value: 'sn:+221' },
  { flag: '🇷🇸', label: 'Serbia', value: 'rs:+381' },
  { flag: '🇸🇨', label: 'Seychelles', value: 'sc:+248' },
  { flag: '🇸🇱', label: 'Sierra Leona', value: 'sl:+232' },
  { flag: '🇸🇬', label: 'Singapur', value: 'sg:+65' },
  { flag: '🇸🇽', label: 'Sint Maarten', value: 'sx:+1' },
  { flag: '🇸🇾', label: 'Siria', value: 'sy:+963' },
  { flag: '🇸🇴', label: 'Somalia', value: 'so:+252' },
  { flag: '🇱🇰', label: 'Sri Lanka', value: 'lk:+94' },
  { flag: '🇿🇦', label: 'Sudáfrica', value: 'za:+27' },
  { flag: '🇸🇩', label: 'Sudán', value: 'sd:+249' },
  { flag: '🇸🇸', label: 'Sudán del Sur', value: 'ss:+211' },
  { flag: '🇸🇪', label: 'Suecia', value: 'se:+46' },
  { flag: '🇨🇭', label: 'Suiza', value: 'ch:+41' },
  { flag: '🇸🇷', label: 'Surinam', value: 'sr:+597' },
  { flag: '🇸🇯', label: 'Svalbard y Jan Mayen', value: 'sj:+4779' },
  { flag: '🇹🇭', label: 'Tailandia', value: 'th:+66' },
  { flag: '🇹🇼', label: 'Taiwán', value: 'tw:+886' },
  { flag: '🇹🇿', label: 'Tanzania', value: 'tz:+255' },
  { flag: '🇹🇯', label: 'Tayikistán', value: 'tj:+992' },
  { flag: '🇮🇴', label: 'Territorio Británico del Océano Índico', value: 'io:+246' },
  { flag: '🇹🇫', label: 'Territorios Australes Franceses', value: 'tf:+262' },
  { flag: '🇵🇸', label: 'Territorios Palestinos', value: 'ps:+970' },
  { flag: '🇹🇱', label: 'Timor-Leste', value: 'tl:+670' },
  { flag: '🇹🇬', label: 'Togo', value: 'tg:+228' },
  { flag: '🇹🇰', label: 'Tokelau', value: 'tk:+690' },
  { flag: '🇹🇴', label: 'Tonga', value: 'to:+676' },
  { flag: '🇹🇹', label: 'Trinidad y Tobago', value: 'tt:+1' },
  { flag: '🇹🇳', label: 'Túnez', value: 'tn:+216' },
  { flag: '🇹🇲', label: 'Turkmenistán', value: 'tm:+993' },
  { flag: '🇹🇷', label: 'Turquía', value: 'tr:+90' },
  { flag: '🇹🇻', label: 'Tuvalu', value: 'tv:+688' },
  { flag: '🇺🇦', label: 'Ucrania', value: 'ua:+380' },
  { flag: '🇺🇬', label: 'Uganda', value: 'ug:+256' },
  { flag: '🇺🇾', label: 'Uruguay', value: 'uy:+598' },
  { flag: '🇺🇿', label: 'Uzbekistán', value: 'uz:+998' },
  { flag: '🇻🇺', label: 'Vanuatu', value: 'vu:+678' },
  { flag: '🇻🇪', label: 'Venezuela', value: 've:+58' },
  { flag: '🇻🇳', label: 'Vietnam', value: 'vn:+84' },
  { flag: '🇼🇫', label: 'Wallis y Futuna', value: 'wf:+681' },
  { flag: '🇾🇪', label: 'Yemen', value: 'ye:+967' },
  { flag: '🇩🇯', label: 'Yibuti', value: 'dj:+253' },
  { flag: '🇿🇲', label: 'Zambia', value: 'zm:+260' },
  { flag: '🇿🇼', label: 'Zimbabue', value: 'zw:+263' },
] as const satisfies readonly WhatsappPrefixOption[];
